"use client";
import "../styles/globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/navbar";
import { Inter } from "next/font/google";
import Footer from "@/components/footer";
import { useState } from "react";
import { Link } from "lucide-react";
import { useRef } from "react";
import { useInView } from "framer-motion";
import Footer1 from "@/components/footer1";
const inter = Inter({ subsets: ["latin"] });

function Section({ children }: any) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  return (
    <div ref={ref}>
      <span
        style={{
          transform: isInView ? "none" : "translateX(-200px)",
          opacity: isInView ? 1 : 0,
          transition: "all 0.2s cubic-bezier(0.17, 0.55, 0.55, 1) 0.2s",
        }}
      >
        {children}
      </span>
    </div>
  );
}

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Section>
          <Navbar />
        </Section>
        {children}
        <Section>
          <Footer1 />
        </Section>
        <Section>
          <Footer />
        </Section>
      </body>
    </html>
  );
}
